export let tasks = [{
  title: "Task 1",
  id: '1',
  description: "bla bla bla",
  status: "Done",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 2",
  id: '2',
  description: "bla bla bla",
  status: "In process",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 3",
  id: '3',
  description: "bla bla bla",
  status: "In process",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 4",
  id: '4',
  description: "bla bla bla",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 5",
  id: '5',
  description: "bla bla blacksnvkjdfvndfjkvdbvjhfdbvjdbfvjhfdbjvdhbfvkdfbvjhbdvjdbfjv",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 6",
  id: '6',
  description: "bla bla bla",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 7",
  id: '7',
  description: "bla bla bla",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 8",
  id: '8',
  description: "bla bla bla",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}, {
  title: "Task 9",
  id: '9',
  description: "bla bla bla",
  status: "Not started",
  startDate: "N/D",
  dateEnd: "N/D",
}];